# Series Data Type

- Numpy's ndarray + 숫자가 아닌 다른 type의 index(ex. 문자열)

In [1]:
import pandas as pd 
import numpy as np 

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
s1 = pd.Series([1,2,3,4])
s1

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
# 1. Series 생성 방법 : list 전달
s2 = pd.Series(
    [1,2,3,4],
    index = ['a', 'b', 'c', 'd']
)
s2

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
# 2. Series 생성 방법 : dictionary 전달
s2 = pd.Series(
  {'a':1, 'b':2, 'c':3, 'd':4 }
)
s2

a    1
b    2
c    3
d    4
dtype: int64

nan 과 관련된 함수

In [5]:
np.nan

nan

In [6]:
# nan 이 포함되면 해당 data type은 float 형으로
s = pd.Series([10, 0, 1, 2, 3, 4, 5, 6, np.nan])
s
len(s)
s.shape      # nan 포함
s.count()   # nan 제외

0    10.0
1     0.0
2     1.0
3     2.0
4     3.0
5     4.0
6     5.0
7     6.0
8     NaN
dtype: float64

9

(9,)

8

In [7]:
s.unique()              # nan 포함
s.value_counts()    # Series 형태로 반환, 데이터 값의 개수, nan 미포함

array([10.,  0.,  1.,  2.,  3.,  4.,  5.,  6., nan])

6.0     1
5.0     1
4.0     1
3.0     1
2.0     1
1.0     1
0.0     1
10.0    1
dtype: int64

### index label을 기준으로 Series간의 operation이 일어남
- Data의 순서가 아니라 index label이 자동으로 정렬되어 연산이 진행됨!

In [8]:
s3 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s4 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s3
s4
s3 + s4

a    1
b    2
c    3
d    4
dtype: int64

d    4
c    3
b    2
a    1
dtype: int64

a    2
b    4
c    6
d    8
dtype: int64

# DataFrame Data type
- 다수의 Series를 하나의 변수로 관리할 수 있도록 만든 자료형
    - Series의 dict 형태라고 보면 됨
        - {'컬럼명1':Series1, '컬럼명2':Series2}
        - 각 Series는 DataFrame의 column을 이룸
        - 당연히 DataFrame을 이루는 Series 간은 index는 모두 동일

## DataFrame을 만드는 다양한 방법들

In [9]:
s1 = np.arange(1, 6, 1)
s2 = np.arange(6, 11, 1)
s1
s2

array([1, 2, 3, 4, 5])

array([ 6,  7,  8,  9, 10])

In [10]:
pd.DataFrame(
    {
        'c1' : s1,
        'c2' : s2
    }
)

c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

## DataFrame 생성시, Series 간의 Index 기준으로 자동정렬

## Reindexing
- 새로운 index label을 기반으로 기존의 'index-value' mapping은 유지한채 재배열하는것

In [16]:
s = pd.Series([1, 2, 3, 4, 5])
s
## index 자체를 바꾸는 것.
s.index = list('abcde') 
s.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [17]:
df

NameError: name 'df' is not defined